### ISSUE TITLE
why it can't work on iphone

### ISSUE THREAD

**Issue by petyou** [boblauer/react-onclickout#12] opened 2016-12-20 06:44 UTC
it can work on Android Wechat and chrome and so on ,but it cant't work on iphone Wechat, 
how to solve it

**Comment by boblauer** [comment] 2017-01-03 18:32
Do you just mean it doesn't work on iphone browser in general?

**Comment by skywickenden** [comment] 2017-01-10 13:08
I have the same problem. Tested on iPhone and iPad using both Safari and Chrome. It doesn't work on any. Works fine on android.

**Comment by skywickenden** [comment] 2017-01-10 14:53
The problem is the click events. They also need to be touchstartevents

		setTimeout(function() {
		  if (self.__unmounted) return;
		  window.addEventListener('click', self.__windowListener);
		  window.addEventListener('touchstart', self.__windowListener);
		  el.addEventListener('click', self.__elementListener);
		  el.addEventListener('touchstart', self.__elementListener);
		}, 0);

This is still not ideal as they will fire on drag as well as touch, but it is far better than not working.

**Comment by boblauer** [comment] 2017-01-10 15:29
Thanks for pointing me in the right direction.  As far as ignoring drag events, I'll probably listen to `touchstart` and `touchend`, and measure the pointer distance between the two.  If it's less than some threshold, I will consider it a click, otherwise I'll consider it a drag and ignore it.

**Comment by skywickenden** [comment] 2017-01-10 15:42
The way to go seems to be to detect touchstart, touchmove and touchend. But only fire the actual even if touchend fires and touchmove did not.  See http://www.webdeveloper.com/forum/showthread.php?272103-onclick-not-working-on-iPhone

**Comment by boblauer** [comment] 2017-01-10 15:48
I considered that as well, but wondered how sensitive the `touchmove` event is.  I'll have to play around with it and see what works best.

**Comment by skywickenden** [comment] 2017-01-11 17:30
If it helps I created a fork [here](https://github.com/skywickenden/react-onclickout/blob/master/index.js) using the touchmove method. It seems to work fine. (I only edited the compiled file and not the source one.)

**Comment by richardwillars** [comment] 2017-05-30 15:25
Any chance of the above fix getting merged in?

**Comment by boblauer** [comment] 2017-05-30 15:47
Yeah, sorry, I completely forgot about this.  I will try to get this fixed by the end of this week.

**Comment by richardwillars** [comment] 2017-05-31 08:05
Amazing, thanks :)

**Comment by fpanwaskar-hive** [comment] 2017-06-05 15:04
Hi @boblauer any idea when you will be able to merge this in please?  This would solve a bug for us, thanks in advance.

**Comment by boblauer** [comment] 2017-06-05 16:24
This has been published, `react-onclickout@2.0.7`.  If you see any issues on iOS, please let me know.  I don't have an iOS device, so I could only test this inside of an iOS simulator.

**Closed by boblauer** 2017-06-05 16:24 UTC
